#!/usr/bin/env node
/**
 * Course Engine Build Script
 *
 * Reads course.json manifest + content files (markdown lessons, JSON exercises,
 * JSON flashcards) + engine templates, and produces a complete static site in dist/.
 *
 * Only dependency: marked (for markdown → HTML)
 *
 * Usage: node build.js
 */

const fs = require('fs');
const path = require('path');
const { marked } = require('marked');

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------
const ROOT = __dirname;
const CONTENT_DIR = path.join(ROOT, 'content');
const ENGINE_DIR = path.join(ROOT, 'engine');
const DIST_DIR = path.join(ROOT, 'dist');

const LESSONS_DIR = path.join(CONTENT_DIR, 'lessons');
const EXERCISES_DIR = path.join(CONTENT_DIR, 'exercises');
const FLASHCARDS_DIR = path.join(CONTENT_DIR, 'flashcards');
const ASSETS_DIR = path.join(CONTENT_DIR, 'assets');

const TEMPLATES_DIR = path.join(ENGINE_DIR, 'templates');
const JS_DIR = path.join(ENGINE_DIR, 'js');
const CSS_DIR = path.join(ENGINE_DIR, 'css');
const THEMES_DIR = path.join(ENGINE_DIR, 'themes');

// ---------------------------------------------------------------------------
// 1. Load & validate course.json
// ---------------------------------------------------------------------------
console.log('Loading course.json...');
const courseJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'course.json'), 'utf8'));
const { course, tracks, modules, projects, annotationTypes } = courseJson;

if (!course || !course.name || !course.slug) {
    console.error('Error: course.json must have course.name and course.slug');
    process.exit(1);
}

// ---------------------------------------------------------------------------
// 2. Prepare dist directory
// ---------------------------------------------------------------------------
function mkdirp(dir) {
    fs.mkdirSync(dir, { recursive: true });
}

// Clean and recreate dist
if (fs.existsSync(DIST_DIR)) {
    fs.rmSync(DIST_DIR, { recursive: true, force: true });
}
mkdirp(DIST_DIR);
mkdirp(path.join(DIST_DIR, 'data'));
mkdirp(path.join(DIST_DIR, 'themes'));

// ---------------------------------------------------------------------------
// 3. Compute derived data
// ---------------------------------------------------------------------------

// Module names map: { 0: "Go Quick Reference", 1: "Go Fundamentals", ... }
const moduleNames = {};
modules.forEach(m => { moduleNames[m.id] = m.title; });

// Modules with exercises
const modulesWithExercises = modules.filter(m => m.hasExercises).map(m => m.id);
const modulesWithoutExercises = modules.filter(m => !m.hasExercises).map(m => m.id);

// Sidebar pages: ordered list of { file, label, type }
// Modules and projects interleaved (projects after their afterModule)
const sidebarPages = [];
const projectsByAfterModule = {};
projects.forEach(p => {
    if (!projectsByAfterModule[p.afterModule]) projectsByAfterModule[p.afterModule] = [];
    projectsByAfterModule[p.afterModule].push(p);
});

modules.forEach(m => {
    sidebarPages.push({
        file: m.file + '.html',
        label: `Module ${m.num}: ${m.title}`,
        type: 'module',
        id: m.id
    });
    // Insert projects that come after this module
    if (projectsByAfterModule[m.id]) {
        projectsByAfterModule[m.id].forEach(p => {
            sidebarPages.push({
                file: p.file + '.html',
                label: `Project ${p.num}: ${p.title}`,
                type: 'project',
                id: p.id
            });
        });
    }
});

// Also add standalone pages
sidebarPages.push({ file: 'flashcards.html', label: 'Flashcards', type: 'feature' });
sidebarPages.push({ file: 'daily-practice.html', label: 'Daily Practice', type: 'feature' });
sidebarPages.push({ file: 'analytics.html', label: 'Weak Concepts', type: 'feature' });

// ---------------------------------------------------------------------------
// 4. Generate course-data.js (window.CourseConfig)
// ---------------------------------------------------------------------------
console.log('Generating course-data.js...');
const courseConfigData = {
    course: course,
    tracks: tracks,
    modules: modules,
    projects: projects,
    annotationTypes: annotationTypes,
    // Computed data
    moduleNames: moduleNames,
    modulesWithExercises: modulesWithExercises,
    modulesWithoutExercises: modulesWithoutExercises,
    sidebarPages: sidebarPages
};

fs.writeFileSync(
    path.join(DIST_DIR, 'course-data.js'),
    `// Auto-generated by build.js — do not edit\nwindow.CourseConfig = ${JSON.stringify(courseConfigData, null, 2)};\n`
);

// ---------------------------------------------------------------------------
// 5. Theme links HTML (used in all templates)
// ---------------------------------------------------------------------------
const themeFiles = fs.readdirSync(
    fs.existsSync(THEMES_DIR) ? THEMES_DIR : path.join(ROOT, 'themes')
).filter(f => f.endsWith('.css')).sort();

const themeLinksHtml = themeFiles.map(f =>
    `    <link rel="stylesheet" href="themes/${f}">`
).join('\n');

// ---------------------------------------------------------------------------
// 6. Load templates
// ---------------------------------------------------------------------------
function loadTemplate(name) {
    return fs.readFileSync(path.join(TEMPLATES_DIR, name), 'utf8');
}

const moduleTemplate = loadTemplate('module.html');
const projectTemplate = loadTemplate('project.html');
const indexTemplate = loadTemplate('index.html');
const flashcardsTemplate = loadTemplate('flashcards.html');
const dailyPracticeTemplate = loadTemplate('daily-practice.html');
const analyticsTemplate = loadTemplate('analytics.html');

// ---------------------------------------------------------------------------
// 7. Configure marked
// ---------------------------------------------------------------------------
marked.setOptions({
    gfm: true,
    breaks: false
});

// ---------------------------------------------------------------------------
// 8. Helper: build navigation links and buttons
// ---------------------------------------------------------------------------
function buildNavLinks(currentFile) {
    return `            <a href="index.html" class="nav-btn prev-btn">&larr; Dashboard</a>`;
}

function buildNavButtons(currentFile) {
    // Find current page index in sidebar pages
    const idx = sidebarPages.findIndex(p => p.file === currentFile);
    let html = '        <div class="nav-buttons">\n';

    if (idx > 0) {
        const prev = sidebarPages[idx - 1];
        html += `            <a href="${prev.file}" class="nav-btn prev-btn">&larr; ${prev.label}</a>\n`;
    } else {
        html += `            <a href="index.html" class="nav-btn prev-btn">&larr; Dashboard</a>\n`;
    }

    if (idx >= 0 && idx < sidebarPages.length - 1) {
        const next = sidebarPages[idx + 1];
        html += `            <a href="${next.file}" class="nav-btn next-btn">${next.label} &rarr;</a>\n`;
    }

    html += '        </div>';
    return html;
}

// ---------------------------------------------------------------------------
// 9. Build exercise scripts for modules with exercises
// ---------------------------------------------------------------------------
function buildExerciseScripts(moduleId) {
    const mod = modules.find(m => m.id === moduleId);
    if (!mod || !mod.hasExercises) return '';
    return `    <script src="course.js"></script>\n    <script src="exercise-renderer.js"></script>\n    <script src="module-loader.js"></script>`;
}

// ---------------------------------------------------------------------------
// 10. Generate module HTML pages
// ---------------------------------------------------------------------------
console.log('Generating module pages...');
modules.forEach(mod => {
    const mdFile = path.join(LESSONS_DIR, mod.file + '.md');
    if (!fs.existsSync(mdFile)) {
        console.warn(`  Warning: ${mod.file}.md not found, skipping`);
        return;
    }

    const mdContent = fs.readFileSync(mdFile, 'utf8');
    const htmlContent = marked.parse(mdContent);
    const currentFile = mod.file + '.html';

    let page = moduleTemplate
        .replace(/\{\{COURSE_NAME\}\}/g, course.name)
        .replace(/\{\{TITLE\}\}/g, mod.title)
        .replace(/\{\{MODULE_NUM\}\}/g, mod.num)
        .replace(/\{\{MODULE_ID\}\}/g, String(mod.id))
        .replace(/\{\{MODULE_DESC\}\}/g, mod.description)
        .replace('{{LESSON_CONTENT}}', htmlContent)
        .replace('{{THEME_LINKS}}', themeLinksHtml)
        .replace('{{NAV_LINKS}}', buildNavLinks(currentFile))
        .replace('{{NAV_BUTTONS}}', buildNavButtons(currentFile))
        .replace('{{SCRIPTS}}', buildExerciseScripts(mod.id));

    fs.writeFileSync(path.join(DIST_DIR, currentFile), page);
    console.log(`  ${currentFile}`);
});

// ---------------------------------------------------------------------------
// 11. Generate project HTML pages
// ---------------------------------------------------------------------------
console.log('Generating project pages...');
projects.forEach(proj => {
    const mdFile = path.join(LESSONS_DIR, proj.file + '.md');
    if (!fs.existsSync(mdFile)) {
        console.warn(`  Warning: ${proj.file}.md not found, skipping`);
        return;
    }

    const mdContent = fs.readFileSync(mdFile, 'utf8');
    const htmlContent = marked.parse(mdContent);
    const currentFile = proj.file + '.html';

    let page = projectTemplate
        .replace(/\{\{COURSE_NAME\}\}/g, course.name)
        .replace(/\{\{TITLE\}\}/g, proj.title)
        .replace(/\{\{MODULE_DESC\}\}/g, proj.description)
        .replace('{{LESSON_CONTENT}}', htmlContent)
        .replace('{{THEME_LINKS}}', themeLinksHtml)
        .replace('{{NAV_LINKS}}', buildNavLinks(currentFile))
        .replace('{{NAV_BUTTONS}}', buildNavButtons(currentFile));

    fs.writeFileSync(path.join(DIST_DIR, currentFile), page);
    console.log(`  ${currentFile}`);
});

// ---------------------------------------------------------------------------
// 12. Generate index.html (dashboard)
// ---------------------------------------------------------------------------
console.log('Generating index.html...');

function buildModuleListHtml() {
    let html = '';

    // Track sections
    tracks.forEach(track => {
        html += `            <!-- Track ${track.id} -->\n`;
        html += `            <div class="track-section">\n`;
        html += `                <div class="track-title">Track ${track.id} • ${track.title}</div>\n`;

        track.modules.forEach(modId => {
            const mod = modules.find(m => m.id === modId);
            if (!mod) return;
            html += `                <div class="module-item" data-module="${mod.id}">\n`;
            html += `                    <input type="checkbox" class="module-checkbox" id="m${mod.id}">\n`;
            html += `                    <a href="${mod.file}.html" class="module-link">\n`;
            html += `                        <span class="module-num">MODULE ${mod.num}</span>\n`;
            html += `                        <span class="module-name">${mod.title}</span>\n`;
            html += `                    </a>\n`;
            html += `                    <span class="exercise-progress-inline" id="ex-progress-${mod.id}"></span>\n`;
            html += `                    <span class="last-studied" id="last-${mod.id}"></span>\n`;
            html += `                </div>\n`;
        });

        html += `            </div>\n\n`;
    });

    // Projects section
    html += `            <!-- Projects -->\n`;
    html += `            <div class="track-section">\n`;
    html += `                <div class="track-title">Projects • Capstone</div>\n`;

    projects.forEach(proj => {
        html += `                <div class="module-item" data-module="${proj.id}">\n`;
        html += `                    <input type="checkbox" class="module-checkbox" id="m${proj.id}">\n`;
        html += `                    <a href="${proj.file}.html" class="module-link">\n`;
        html += `                        <span class="module-num">PROJECT ${proj.num}</span>\n`;
        html += `                        <span class="module-name">${proj.title}</span>\n`;
        html += `                    </a>\n`;
        html += `                    <span class="last-studied" id="last-${proj.id}"></span>\n`;
        html += `                </div>\n`;
    });

    html += `            </div>\n`;
    return html;
}

// Build module filter buttons for daily-practice
function buildModuleFilterButtons() {
    let html = '                    <button class="dp-option active" data-module="all">All</button>\n';
    modules.forEach(mod => {
        if (mod.id === 0) return; // skip reference module
        html += `                    <button class="dp-option" data-module="${mod.id}">M${mod.id}</button>\n`;
    });
    return html;
}

const moduleCount = modules.filter(m => m.id > 0).length; // exclude reference module from count

let indexPage = indexTemplate
    .replace(/\{\{COURSE_NAME\}\}/g, course.name)
    .replace(/\{\{COURSE_DESCRIPTION\}\}/g, course.description)
    .replace(/\{\{MODULE_COUNT\}\}/g, String(moduleCount))
    .replace('{{THEME_LINKS}}', themeLinksHtml)
    .replace('{{MODULE_LIST}}', buildModuleListHtml());

fs.writeFileSync(path.join(DIST_DIR, 'index.html'), indexPage);
console.log('  index.html');

// ---------------------------------------------------------------------------
// 13. Generate flashcards page
// ---------------------------------------------------------------------------
console.log('Generating flashcards.html...');
let flashcardsPage = flashcardsTemplate
    .replace(/\{\{COURSE_NAME\}\}/g, course.name)
    .replace('{{THEME_LINKS}}', themeLinksHtml);

fs.writeFileSync(path.join(DIST_DIR, 'flashcards.html'), flashcardsPage);
console.log('  flashcards.html');

// ---------------------------------------------------------------------------
// 14. Generate daily-practice page
// ---------------------------------------------------------------------------
console.log('Generating daily-practice.html...');
let dpPage = dailyPracticeTemplate
    .replace(/\{\{COURSE_NAME\}\}/g, course.name)
    .replace('{{THEME_LINKS}}', themeLinksHtml)
    .replace('{{MODULE_FILTER_BUTTONS}}', buildModuleFilterButtons());

fs.writeFileSync(path.join(DIST_DIR, 'daily-practice.html'), dpPage);
console.log('  daily-practice.html');

// ---------------------------------------------------------------------------
// 15. Generate analytics page
// ---------------------------------------------------------------------------
console.log('Generating analytics.html...');
let analyticsPage = analyticsTemplate
    .replace(/\{\{COURSE_NAME\}\}/g, course.name)
    .replace('{{THEME_LINKS}}', themeLinksHtml);

fs.writeFileSync(path.join(DIST_DIR, 'analytics.html'), analyticsPage);
console.log('  analytics.html');

// ---------------------------------------------------------------------------
// 16. Compile exercise JSON → JS (for browser loading)
// ---------------------------------------------------------------------------
console.log('Compiling exercise data...');
const exerciseFiles = fs.existsSync(EXERCISES_DIR)
    ? fs.readdirSync(EXERCISES_DIR).filter(f => f.match(/^module\d+-variants\.json$/))
    : [];

exerciseFiles.forEach(jsonFile => {
    const jsonPath = path.join(EXERCISES_DIR, jsonFile);
    const jsFile = jsonFile.replace('.json', '.js');
    const data = fs.readFileSync(jsonPath, 'utf8');

    // Validate JSON
    try {
        JSON.parse(data);
    } catch (e) {
        console.error(`  Invalid JSON in ${jsonFile}:`, e.message);
        process.exit(1);
    }

    const moduleNum = jsonFile.match(/module(\d+)/)[1];

    const js = `// Auto-generated from ${jsonFile} - do not edit directly\nwindow.moduleData = ${data};\nwindow.moduleDataRegistry = window.moduleDataRegistry || {};\nwindow.moduleDataRegistry[${moduleNum}] = window.moduleData;\n`;

    fs.writeFileSync(path.join(DIST_DIR, 'data', jsFile), js);
    console.log(`  data/${jsFile}`);
});

// ---------------------------------------------------------------------------
// 17. Generate flashcard-data.js
// ---------------------------------------------------------------------------
console.log('Generating flashcard-data.js...');
const flashcardJsonPath = path.join(FLASHCARDS_DIR, 'flashcards.json');
if (fs.existsSync(flashcardJsonPath)) {
    const flashcardData = fs.readFileSync(flashcardJsonPath, 'utf8');
    // Validate
    try {
        JSON.parse(flashcardData);
    } catch (e) {
        console.error('  Invalid JSON in flashcards.json:', e.message);
        process.exit(1);
    }
    fs.writeFileSync(
        path.join(DIST_DIR, 'flashcard-data.js'),
        `// Auto-generated from flashcards.json - do not edit directly\nwindow.FlashcardData = ${flashcardData};\n`
    );
    console.log('  flashcard-data.js');
} else {
    console.warn('  Warning: flashcards.json not found, skipping flashcard-data.js');
}

// ---------------------------------------------------------------------------
// 18. Copy engine JS files
// ---------------------------------------------------------------------------
console.log('Copying engine JS files...');
if (fs.existsSync(JS_DIR)) {
    fs.readdirSync(JS_DIR).filter(f => f.endsWith('.js')).forEach(file => {
        fs.copyFileSync(path.join(JS_DIR, file), path.join(DIST_DIR, file));
        console.log(`  ${file}`);
    });
}

// ---------------------------------------------------------------------------
// 19. Copy engine CSS files
// ---------------------------------------------------------------------------
console.log('Copying CSS files...');
const cssSource = fs.existsSync(CSS_DIR) ? CSS_DIR : ROOT;
const styleCss = path.join(cssSource, 'style.css');
if (fs.existsSync(styleCss)) {
    fs.copyFileSync(styleCss, path.join(DIST_DIR, 'style.css'));
    console.log('  style.css');
} else if (fs.existsSync(path.join(ROOT, 'style.css'))) {
    fs.copyFileSync(path.join(ROOT, 'style.css'), path.join(DIST_DIR, 'style.css'));
    console.log('  style.css (from root)');
}

// ---------------------------------------------------------------------------
// 20. Copy theme CSS files
// ---------------------------------------------------------------------------
console.log('Copying theme files...');
const themesSource = fs.existsSync(THEMES_DIR) ? THEMES_DIR : path.join(ROOT, 'themes');
if (fs.existsSync(themesSource)) {
    fs.readdirSync(themesSource).filter(f => f.endsWith('.css')).forEach(file => {
        fs.copyFileSync(path.join(themesSource, file), path.join(DIST_DIR, 'themes', file));
        console.log(`  themes/${file}`);
    });
}

// ---------------------------------------------------------------------------
// 21. Copy assets (favicon, etc.)
// ---------------------------------------------------------------------------
console.log('Copying assets...');
if (fs.existsSync(ASSETS_DIR)) {
    fs.readdirSync(ASSETS_DIR).forEach(file => {
        fs.copyFileSync(path.join(ASSETS_DIR, file), path.join(DIST_DIR, file));
        console.log(`  ${file}`);
    });
} else if (fs.existsSync(path.join(ROOT, 'favicon.svg'))) {
    fs.copyFileSync(path.join(ROOT, 'favicon.svg'), path.join(DIST_DIR, 'favicon.svg'));
    console.log('  favicon.svg (from root)');
}

// ---------------------------------------------------------------------------
// 22. Generate sw.js (service worker)
// ---------------------------------------------------------------------------
console.log('Generating sw.js...');

// Scan dist/ for all files to cache
function collectDistFiles(dir, base) {
    let files = [];
    fs.readdirSync(dir).forEach(entry => {
        const fullPath = path.join(dir, entry);
        const relPath = base ? base + '/' + entry : entry;
        if (fs.statSync(fullPath).isDirectory()) {
            files = files.concat(collectDistFiles(fullPath, relPath));
        } else if (entry !== 'sw.js') {
            files.push(relPath);
        }
    });
    return files;
}

const distFiles = collectDistFiles(DIST_DIR, '');
const cacheVersion = Date.now();

const swContent = `// Service Worker for ${course.name} — offline support
// Auto-generated by build.js
// Network-first strategy: always fresh, cache for offline fallback

var CACHE_NAME = '${course.slug}-v${cacheVersion}';

var ASSETS = ${JSON.stringify(distFiles, null, 4)};

// Install: cache all assets, activate immediately
self.addEventListener('install', function(event) {
    event.waitUntil(
        caches.open(CACHE_NAME).then(function(cache) {
            return cache.addAll(ASSETS);
        })
    );
    self.skipWaiting();
});

// Fetch: network-first, fall back to cache when offline
self.addEventListener('fetch', function(event) {
    event.respondWith(
        fetch(event.request).then(function(response) {
            if (response.ok) {
                var clone = response.clone();
                caches.open(CACHE_NAME).then(function(cache) {
                    cache.put(event.request, clone);
                });
            }
            return response;
        }).catch(function() {
            return caches.match(event.request);
        })
    );
});

// Activate: clean old caches, take control of all pages immediately
self.addEventListener('activate', function(event) {
    event.waitUntil(
        caches.keys().then(function(names) {
            return Promise.all(
                names.filter(function(name) {
                    return name !== CACHE_NAME;
                }).map(function(name) {
                    return caches.delete(name);
                })
            );
        }).then(function() {
            return self.clients.claim();
        })
    );
});
`;

fs.writeFileSync(path.join(DIST_DIR, 'sw.js'), swContent);
console.log('  sw.js');

// ---------------------------------------------------------------------------
// Done
// ---------------------------------------------------------------------------
const totalFiles = collectDistFiles(DIST_DIR, '').length + 1; // +1 for sw.js
console.log(`\nBuild complete! ${totalFiles} files generated in dist/`);
